ci/build-images: fix push to ECR (#1315)
Push to ECR started to fail after
https://github.com/neondatabase/autoscaling/pull/1312 changes:

```
Copy neondatabase/neonvm-controller:testrelease-20250311.1c7bb48.13791913752 to dev ECR
ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

It tries to push images to `<ECR>/neondatabase/<IMAGE_NAME>` instead of
`<ECR>/<IMAGE_NAME>`